"""
document_draft_generator.py

Generates professional healthcare administrative
documents based on extracted information.

Generated Documents
-------------------
1. Prior Authorization Request
2. Patient Follow-up Email
3. Payor Cover Letter

Author: Healthcare AI Engine
"""

from __future__ import annotations

from datetime import datetime
from typing import Dict, Any


class DocumentDraftGenerator:

    def __init__(self):
        pass

    # =====================================================
    # Helper Methods
    # =====================================================

    def _safe(self, value, default="N/A"):

        if value is None:
            return default

        if isinstance(value, list):
            if len(value) == 0:
                return default
            return ", ".join(value)

        if str(value).strip() == "":
            return default

        return str(value)

    def _missing_fields_text(self, validation_result):

        missing = validation_result.get("missing_fields", [])

        if not missing:
            return "None"

        output = []

        for item in missing:

            if isinstance(item, dict):

                label = item.get("label", "Unknown")

                reason = item.get("reason", "")

                output.append(f"- {label}: {reason}")

            else:

                output.append(f"- {item}")

        return "\n".join(output)

    # =====================================================
    # Prior Authorization Request
    # =====================================================

    def generate_prior_auth_request(

        self,

        extracted_fields: Dict[str, Any],

        validation_result: Dict[str, Any]

    ) -> str:

        patient_name = self._safe(
            extracted_fields.get("patient_name"),
            "[PATIENT NAME]"
        )

        dob = self._safe(
            extracted_fields.get("dob"),
            "[DOB]"
        )

        member_id = self._safe(
            extracted_fields.get("member_id"),
            "[MEMBER ID]"
        )

        provider = self._safe(
            extracted_fields.get("requesting_provider")
            or extracted_fields.get("physician"),
            "[PROVIDER]"
        )

        provider_npi = self._safe(
            extracted_fields.get("provider_npi")
        )

        insurance = self._safe(
            extracted_fields.get("insurance_provider")
        )

        facility = self._safe(
            extracted_fields.get("facility_name"),
            "Healthcare Facility"
        )

        cpt = self._safe(
            extracted_fields.get("cpt_codes")
            or extracted_fields.get("cpt_code")
        )

        icd10 = self._safe(
            extracted_fields.get("icd10_codes")
            or extracted_fields.get("icd10")
        )

        diagnosis = self._safe(
            extracted_fields.get("diagnosis")
        )

        procedure = self._safe(
            extracted_fields.get("procedure")
        )

        clinical = self._safe(
            extracted_fields.get("clinical_justification"),
            "Clinical notes attached."
        )

        urgency = self._safe(
            extracted_fields.get("urgency"),
            "Standard"
        )

        completeness = validation_result.get(
            "completion",
            validation_result.get(
                "completeness_score",
                0
            )
        )

        missing = self._missing_fields_text(
            validation_result
        )

        draft = f"""
================================================================================
                PRIOR AUTHORIZATION REQUEST
================================================================================

Date:
{datetime.now().strftime("%d-%m-%Y")}

INSURANCE COMPANY
-----------------
{insurance}

PATIENT INFORMATION
-------------------
Patient Name : {patient_name}

Date of Birth : {dob}

Member ID : {member_id}

FACILITY INFORMATION
--------------------
Facility : {facility}

ORDERING PROVIDER
-----------------
Provider : {provider}

NPI : {provider_npi}

SERVICE DETAILS
---------------
Procedure : {procedure}

Diagnosis : {diagnosis}

CPT Code(s) : {cpt}

ICD-10 Code(s) : {icd10}

Urgency : {urgency}

CLINICAL JUSTIFICATION
----------------------
{clinical}

DOCUMENT VALIDATION
-------------------
Completeness Score : {completeness}%

Missing Fields

{missing}

CERTIFICATION
-------------
This request has been generated by the
Healthcare AI Administrative System.

================================================================================
"""

        return draft

    # =====================================================
    # Patient Follow-up Email
    # =====================================================

    def generate_patient_followup_email(

        self,

        extracted_fields,

        validation_result

    ):

        patient = self._safe(

            extracted_fields.get("patient_name"),

            "Patient"

        )

        insurance = self._safe(

            extracted_fields.get("insurance_provider"),

            "your insurance provider"

        )

        missing = validation_result.get(

            "missing_fields",

            []

        )

        lines = []

        for item in missing:

            if isinstance(item, dict):

                label = item.get(

                    "label",

                    "Unknown"

                )

                reason = item.get(

                    "reason",

                    ""

                )

                lines.append(

                    f"• {label} - {reason}"

                )

            else:

                lines.append(

                    f"• {item}"

                )

        if not lines:

            lines.append(

                "• Please verify your uploaded document."

            )

        email = f"""
Subject: Additional Information Required

Dear {patient},

We are currently processing your healthcare paperwork.

To complete the submission to {insurance},
we require the following information:

{chr(10).join(lines)}

Please upload the missing information
through the patient portal at your earliest convenience.

If you have any questions,
please contact our support team.

Thank you,

Healthcare Administrative Team
"""

        return email

    # =====================================================
    # Payor Cover Letter
    # =====================================================

    def generate_payor_cover_letter(

        self,

        extracted_fields

    ):

        patient = self._safe(

            extracted_fields.get("patient_name")

        )

        dob = self._safe(

            extracted_fields.get("dob")

        )

        member = self._safe(

            extracted_fields.get("member_id")

        )

        provider = self._safe(

            extracted_fields.get("requesting_provider")
            or extracted_fields.get("physician")

        )

        npi = self._safe(

            extracted_fields.get("provider_npi")

        )

        insurance = self._safe(

            extracted_fields.get("insurance_provider")

        )

        cpt = self._safe(

            extracted_fields.get("cpt_codes")
            or extracted_fields.get("cpt_code")

        )

        icd = self._safe(

            extracted_fields.get("icd10_codes")
            or extracted_fields.get("icd10")

        )

        letter = f"""
TO:
{insurance}
Prior Authorization Department

DATE:
{datetime.now().strftime("%d-%m-%Y")}

SUBJECT:
Prior Authorization Request

Patient : {patient}

DOB : {dob}

Member ID : {member}

Ordering Provider : {provider}

Provider NPI : {npi}

Requested Procedure

{cpt}

Diagnosis

{icd}

Please review the attached documentation
and process this authorization request.

Thank you.

Sincerely,

{provider}

Healthcare AI Administrative System
"""

        return letter

    # =====================================================
    # Main Function
    # =====================================================

    def generate_drafts(

        self,

        extracted_fields,

        validation_result,

        doc_type

    ):

        return {

            "document_type": doc_type,

            "prior_auth_request":

                self.generate_prior_auth_request(

                    extracted_fields,

                    validation_result

                ),

            "patient_followup_message":

                self.generate_patient_followup_email(

                    extracted_fields,

                    validation_result

                ),

            "payor_cover_letter":

                self.generate_payor_cover_letter(

                    extracted_fields

                )

        }


# ==========================================================
# Testing
# ==========================================================

if __name__ == "__main__":

    extracted = {

        "patient_name": "John Smith",

        "dob": "12/05/1995",

        "member_id": "BX-92831",

        "insurance_provider": "Blue Cross",

        "physician": "Dr Robert Brown",

        "provider_npi": "9876543210",

        "procedure": "MRI Brain",

        "diagnosis": "Migraine",

        "cpt_code": "70553",

        "icd10": "G43.909",

        "clinical_justification":
        "Patient has persistent headaches despite medication.",

        "urgency": "Urgent"

    }

    validation = {

        "completion": 92,

        "missing_fields": [

            {

                "label": "Policy Number",

                "reason": "Not found in uploaded document"

            }

        ]

    }

    generator = DocumentDraftGenerator()

    drafts = generator.generate_drafts(

        extracted,

        validation,

        "Prior Authorization"

    )

    print(drafts["prior_auth_request"])

    print(drafts["patient_followup_message"])

    print(drafts["payor_cover_letter"])