import { useEffect, useState } from "react";
import Sidebar from "../components/Sidebar";
import { getPatient, getAppointments, uploadFile, extractFields } from "../services/api";
import AiAssistant from "../components/AiAssistant";

const languages = ["English", "Hindi", "Marathi", "Tamil", "Telugu", "Bengali", "Urdu"];
export default function PatientDashboard() {
  const user = JSON.parse(localStorage.getItem("mamacare_user") || "{}"); const [data, setData] = useState(null), [file, setFile] = useState(null), [language, setLanguage] = useState("English"), [chat, setChat] = useState([]), [question, setQuestion] = useState(""), [summary, setSummary] = useState("");
  const load = async () => { if (!user.id) return; const [profile, appts] = await Promise.all([getPatient(user.id), getAppointments({ patient: user.name })]); setData({ ...profile.data, appointments: appts.data }); };
  useEffect(() => { load().catch(() => {}); }, []);
  const upload = async () => { if (!file) return; const fd = new FormData(); fd.append("file", file); fd.append("patient_name", user.name); try { const u = await uploadFile(fd); const e = await extractFields({ ...u.data, language }); setSummary(e.data.ai_summary || "Your report was securely added to your records."); load(); } catch { setSummary("Your report is queued for review. A care team member will update your records shortly."); } };
  const ask = () => { if (!question.trim()) return; const q = question; const answers = { Hindi: "मैं आपकी मदद कर सकता हूँ। लक्षण गंभीर हों, सांस लेने में कठिनाई या सीने में दर्द हो तो तुरंत स्थानीय आपातकालीन सेवा से संपर्क करें।", Marathi: "मी मदत करू शकतो. श्वास घेण्यास त्रास, छातीत दुखणे किंवा गंभीर लक्षणे असल्यास तातडीची वैद्यकीय मदत घ्या।", Tamil: "நான் உதவ முடியும். மூச்சுத்திணறல், மார்பு வலி அல்லது கடுமையான அறிகுறிகள் இருந்தால் உடனடியாக அவசர மருத்துவ உதவியை நாடுங்கள்." }; setChat([...chat, { q, a: answers[language] || "I can help explain your care information. For urgent symptoms such as chest pain, severe breathing difficulty, fainting or heavy bleeding, contact emergency services immediately." }]); setQuestion(""); };
  const docs = data?.documents || [], prescriptions = data?.prescriptions || [], appts = data?.appointments || [];
  return <div className="flex min-h-screen bg-slate-50"><Sidebar role="patient"/><main className="flex-1 p-5 md:p-8 overflow-auto"><div className="flex justify-between items-start mb-7"><div><p className="text-sm text-blue-600 font-semibold">PATIENT PORTAL</p><h1 className="text-2xl font-bold">Welcome, {user.name || "Patient"}</h1><p className="text-sm text-slate-500">Your reports, care plan and appointments in one place.</p></div><select value={language} onChange={e => setLanguage(e.target.value)} className="input w-32">{languages.map(l => <option key={l}>{l}</option>)}</select></div>
  <div className="grid md:grid-cols-4 gap-4 mb-6">{[["Reports", docs.length, "text-blue-600"], ["Appointments", appts.filter(a=>a.status!=="Completed").length, "text-violet-600"], ["Prescriptions", prescriptions.length, "text-emerald-600"], ["Insurance", data?.insurance_status || "Not added", "text-amber-600"]].map(([l,v,c])=><div key={l} className="bg-white rounded-2xl p-4 border border-slate-100"><p className={`text-xl font-bold ${c}`}>{v}</p><p className="text-xs text-slate-500 mt-1">{l}</p></div>)}</div>
  <div className="grid xl:grid-cols-[1.35fr_.9fr] gap-6"><div className="space-y-6"><section className="bg-white rounded-2xl p-5 border border-slate-100"><h2 className="font-semibold">Upload a report</h2><p className="text-sm text-slate-500 mt-1">PDF, image or document—our team will review it before it becomes part of your record.</p><div className="flex gap-3 mt-4 flex-wrap"><input type="file" onChange={e=>setFile(e.target.files[0])} className="text-sm"/><button onClick={upload} className="bg-blue-600 text-white px-4 py-2 rounded-lg text-sm">Upload securely</button></div>{summary && <div className="mt-4 text-sm p-3 bg-blue-50 text-blue-800 rounded-lg">{summary}</div>}</section>
  <section className="bg-white rounded-2xl p-5 border border-slate-100"><h2 className="font-semibold mb-3">Appointments & tokens</h2>{appts.length ? appts.map(a=><div key={a.id} className="py-3 border-t flex justify-between text-sm"><div><b>{a.doctor_name}</b><p className="text-slate-500">{a.appointment_date} · {a.appointment_time} · {a.reason}</p></div><span className="bg-blue-50 text-blue-700 px-2 py-1 rounded-lg h-fit font-medium">{a.token_no} · {a.status}</span></div>) : <p className="text-sm text-slate-500">No appointments yet. The reception desk can book one for you.</p>}</section>
  <section className="bg-white rounded-2xl p-5 border border-slate-100"><h2 className="font-semibold mb-3">Prescriptions & visit history</h2>{prescriptions.length ? prescriptions.map(p=><div key={p.id} className="border-t py-3 text-sm"><b>{p.diagnosis}</b><p className="text-slate-500">Dr. {p.doctor_name.replace(/^Dr\.\s*/, "")} · {p.created_at?.slice(0,10)}</p><p className="mt-1">{p.advice}</p></div>) : <p className="text-sm text-slate-500">Your doctor’s prescriptions will appear here after a consultation.</p>}</section></div>
  <aside className="bg-white rounded-2xl p-5 border border-slate-100 h-fit"><h2 className="font-semibold">Ask Care Assistant</h2><p className="text-xs text-slate-500 mt-1">Ask in {language}. This tool supports information, not emergency diagnosis.</p><div className="mt-4 space-y-3 max-h-80 overflow-auto">{chat.length ? chat.map((x,i)=><div key={i} className="text-sm"><div className="bg-slate-100 p-2 rounded-lg">{x.q}</div><div className="bg-blue-50 text-blue-900 p-2 rounded-lg mt-1">{x.a}</div></div>) : <p className="text-sm text-slate-400">Try: “What should I bring to my appointment?”</p>}</div><div className="mt-4 flex gap-2"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} className="input" placeholder="Ask a question"/><button onClick={ask} className="bg-blue-600 text-white px-3 rounded-lg">Send</button></div></aside></div><AiAssistant /></main></div>;
}
