import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import Sidebar from "../components/Sidebar";
import { searchPatients, getAvailableDoctors, createAppointment, updatePatient } from "../services/api";
export default function ReceptionistDashboard() {
 const [query,setQuery]=useState(""),[patients,setPatients]=useState([]),[selected,setSelected]=useState(null),[doctors,setDoctors]=useState([]),[form,setForm]=useState({reason:"General consultation",doctor_name:"Dr. Arvind Sharma",appointment_date:new Date().toISOString().slice(0,10),appointment_time:"10:30 AM"}),[notice,setNotice]=useState(""); const nav=useNavigate();
 const find=async()=>{try{setPatients((await searchPatients(query)).data)}catch{setNotice("Backend unavailable. Please start the Flask server.")}}; useEffect(()=>{find(); getAvailableDoctors("General Medicine").then(r=>setDoctors(r.data)).catch(()=>{})},[]);
 const book=async()=>{if(!selected)return setNotice("Search for and select a patient first.");try{const r=await createAppointment({...form,patient_name:selected.name});setNotice(`${r.data.appointment.token_no} created for ${selected.name}.`);find()}catch(e){setNotice(e.response?.data?.error||"Could not create appointment.")}};
 const saveInsurance=async()=>{if(!selected)return; await updatePatient(selected.id,{insurance_provider:selected.insurance_provider||"",insurance_policy:selected.insurance_policy||"",insurance_status:"Active"});setNotice("Insurance details saved.")};
 return <div className="flex min-h-screen bg-slate-50"><Sidebar role="receptionist"/><main className="flex-1 p-5 md:p-8"><div className="flex justify-between mb-6"><div><p className="text-sm text-violet-600 font-semibold">FRONT DESK</p><h1 className="text-2xl font-bold">Patient intake & appointment desk</h1><p className="text-sm text-slate-500">Look up a person by mobile, name or email, then create a token in minutes.</p></div><button onClick={()=>nav("/receptionist/workflow")} className="bg-blue-600 text-white px-4 py-2 rounded-xl text-sm h-fit">Upload document</button></div>{notice&&<div className="mb-4 bg-blue-50 text-blue-800 p-3 rounded-xl text-sm">{notice}</div>}
 <div className="grid xl:grid-cols-[.9fr_1.1fr] gap-6"><section className="bg-white rounded-2xl p-5 border border-slate-100"><h2 className="font-semibold">Find patient</h2><div className="flex gap-2 mt-3"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&find()} placeholder="Name, mobile number or email"/><button onClick={find} className="bg-slate-900 text-white px-4 rounded-lg">Search</button></div><div className="mt-4 space-y-2">{patients.map(p=><button key={p.id} onClick={()=>{setSelected(p);setNotice("")}} className={`w-full text-left rounded-xl p-3 border ${selected?.id===p.id?"border-blue-500 bg-blue-50":"border-slate-100 hover:bg-slate-50"}`}><b className="text-sm">{p.name}</b><p className="text-xs text-slate-500">{p.phone||"No mobile"} · {p.email}</p></button>)}</div>{selected&&<div className="mt-5 border-t pt-4"><h3 className="font-semibold text-sm">Insurance status</h3><div className="grid grid-cols-2 gap-2 mt-2"><input className="input" placeholder="Provider" value={selected.insurance_provider||""} onChange={e=>setSelected({...selected,insurance_provider:e.target.value})}/><input className="input" placeholder="Policy number" value={selected.insurance_policy||""} onChange={e=>setSelected({...selected,insurance_policy:e.target.value})}/></div><button onClick={saveInsurance} className="mt-2 text-blue-600 text-sm">Save insurance details</button></div>}</section>
 <section className="bg-white rounded-2xl p-5 border border-slate-100"><h2 className="font-semibold">Make appointment & generate token</h2><p className="text-sm text-slate-500 mt-1">For patients who need help booking, choose the likely specialty and a free doctor.</p><div className="grid md:grid-cols-2 gap-3 mt-4"><input className="input" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Symptoms / reason"/><input type="date" className="input" value={form.appointment_date} onChange={e=>setForm({...form,appointment_date:e.target.value})}/><select className="input" value={form.doctor_name} onChange={e=>setForm({...form,doctor_name:e.target.value})}>{doctors.map(d=><option key={d.name} value={d.name}>{d.name} — {d.specialty} ({d.available?`free ${d.next_slot}`:"next "+d.next_slot})</option>)}</select><input className="input" value={form.appointment_time} onChange={e=>setForm({...form,appointment_time:e.target.value})}/></div><button onClick={book} className="mt-4 w-full bg-blue-600 text-white rounded-xl py-3 font-semibold">Create appointment & token</button><div className="mt-6 p-4 bg-amber-50 rounded-xl"><b className="text-sm text-amber-800">Missing details?</b><p className="text-sm text-amber-700 mt-1">Use the document workflow to extract identity and insurance data. You can review fields manually or send the patient an email/SMS request from that screen.</p></div></section></div></main></div>;
}
